# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_tracking_pid/PidDebug.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class PidDebug(genpy.Message):
  _md5sum = "4e3a85077871d90d16f8de7c7a3cf074"
  _type = "path_tracking_pid/PidDebug"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Error topic containing the 'control' error on which the PID acts
geometry_msgs/Twist control_error
# Error topic containing the 'tracking' error, i.e. the real error between path and tracked link
geometry_msgs/Twist tracking_error
# Control values
geometry_msgs/Twist proportional
geometry_msgs/Twist integral
geometry_msgs/Twist derivative
geometry_msgs/Twist feedforward
float32 steering_angle
float32 steering_yaw_vel
float32 steering_x_vel

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['control_error','tracking_error','proportional','integral','derivative','feedforward','steering_angle','steering_yaw_vel','steering_x_vel']
  _slot_types = ['geometry_msgs/Twist','geometry_msgs/Twist','geometry_msgs/Twist','geometry_msgs/Twist','geometry_msgs/Twist','geometry_msgs/Twist','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       control_error,tracking_error,proportional,integral,derivative,feedforward,steering_angle,steering_yaw_vel,steering_x_vel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PidDebug, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.control_error is None:
        self.control_error = geometry_msgs.msg.Twist()
      if self.tracking_error is None:
        self.tracking_error = geometry_msgs.msg.Twist()
      if self.proportional is None:
        self.proportional = geometry_msgs.msg.Twist()
      if self.integral is None:
        self.integral = geometry_msgs.msg.Twist()
      if self.derivative is None:
        self.derivative = geometry_msgs.msg.Twist()
      if self.feedforward is None:
        self.feedforward = geometry_msgs.msg.Twist()
      if self.steering_angle is None:
        self.steering_angle = 0.
      if self.steering_yaw_vel is None:
        self.steering_yaw_vel = 0.
      if self.steering_x_vel is None:
        self.steering_x_vel = 0.
    else:
      self.control_error = geometry_msgs.msg.Twist()
      self.tracking_error = geometry_msgs.msg.Twist()
      self.proportional = geometry_msgs.msg.Twist()
      self.integral = geometry_msgs.msg.Twist()
      self.derivative = geometry_msgs.msg.Twist()
      self.feedforward = geometry_msgs.msg.Twist()
      self.steering_angle = 0.
      self.steering_yaw_vel = 0.
      self.steering_x_vel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_36d3f().pack(_x.control_error.linear.x, _x.control_error.linear.y, _x.control_error.linear.z, _x.control_error.angular.x, _x.control_error.angular.y, _x.control_error.angular.z, _x.tracking_error.linear.x, _x.tracking_error.linear.y, _x.tracking_error.linear.z, _x.tracking_error.angular.x, _x.tracking_error.angular.y, _x.tracking_error.angular.z, _x.proportional.linear.x, _x.proportional.linear.y, _x.proportional.linear.z, _x.proportional.angular.x, _x.proportional.angular.y, _x.proportional.angular.z, _x.integral.linear.x, _x.integral.linear.y, _x.integral.linear.z, _x.integral.angular.x, _x.integral.angular.y, _x.integral.angular.z, _x.derivative.linear.x, _x.derivative.linear.y, _x.derivative.linear.z, _x.derivative.angular.x, _x.derivative.angular.y, _x.derivative.angular.z, _x.feedforward.linear.x, _x.feedforward.linear.y, _x.feedforward.linear.z, _x.feedforward.angular.x, _x.feedforward.angular.y, _x.feedforward.angular.z, _x.steering_angle, _x.steering_yaw_vel, _x.steering_x_vel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.control_error is None:
        self.control_error = geometry_msgs.msg.Twist()
      if self.tracking_error is None:
        self.tracking_error = geometry_msgs.msg.Twist()
      if self.proportional is None:
        self.proportional = geometry_msgs.msg.Twist()
      if self.integral is None:
        self.integral = geometry_msgs.msg.Twist()
      if self.derivative is None:
        self.derivative = geometry_msgs.msg.Twist()
      if self.feedforward is None:
        self.feedforward = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 300
      (_x.control_error.linear.x, _x.control_error.linear.y, _x.control_error.linear.z, _x.control_error.angular.x, _x.control_error.angular.y, _x.control_error.angular.z, _x.tracking_error.linear.x, _x.tracking_error.linear.y, _x.tracking_error.linear.z, _x.tracking_error.angular.x, _x.tracking_error.angular.y, _x.tracking_error.angular.z, _x.proportional.linear.x, _x.proportional.linear.y, _x.proportional.linear.z, _x.proportional.angular.x, _x.proportional.angular.y, _x.proportional.angular.z, _x.integral.linear.x, _x.integral.linear.y, _x.integral.linear.z, _x.integral.angular.x, _x.integral.angular.y, _x.integral.angular.z, _x.derivative.linear.x, _x.derivative.linear.y, _x.derivative.linear.z, _x.derivative.angular.x, _x.derivative.angular.y, _x.derivative.angular.z, _x.feedforward.linear.x, _x.feedforward.linear.y, _x.feedforward.linear.z, _x.feedforward.angular.x, _x.feedforward.angular.y, _x.feedforward.angular.z, _x.steering_angle, _x.steering_yaw_vel, _x.steering_x_vel,) = _get_struct_36d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_36d3f().pack(_x.control_error.linear.x, _x.control_error.linear.y, _x.control_error.linear.z, _x.control_error.angular.x, _x.control_error.angular.y, _x.control_error.angular.z, _x.tracking_error.linear.x, _x.tracking_error.linear.y, _x.tracking_error.linear.z, _x.tracking_error.angular.x, _x.tracking_error.angular.y, _x.tracking_error.angular.z, _x.proportional.linear.x, _x.proportional.linear.y, _x.proportional.linear.z, _x.proportional.angular.x, _x.proportional.angular.y, _x.proportional.angular.z, _x.integral.linear.x, _x.integral.linear.y, _x.integral.linear.z, _x.integral.angular.x, _x.integral.angular.y, _x.integral.angular.z, _x.derivative.linear.x, _x.derivative.linear.y, _x.derivative.linear.z, _x.derivative.angular.x, _x.derivative.angular.y, _x.derivative.angular.z, _x.feedforward.linear.x, _x.feedforward.linear.y, _x.feedforward.linear.z, _x.feedforward.angular.x, _x.feedforward.angular.y, _x.feedforward.angular.z, _x.steering_angle, _x.steering_yaw_vel, _x.steering_x_vel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.control_error is None:
        self.control_error = geometry_msgs.msg.Twist()
      if self.tracking_error is None:
        self.tracking_error = geometry_msgs.msg.Twist()
      if self.proportional is None:
        self.proportional = geometry_msgs.msg.Twist()
      if self.integral is None:
        self.integral = geometry_msgs.msg.Twist()
      if self.derivative is None:
        self.derivative = geometry_msgs.msg.Twist()
      if self.feedforward is None:
        self.feedforward = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 300
      (_x.control_error.linear.x, _x.control_error.linear.y, _x.control_error.linear.z, _x.control_error.angular.x, _x.control_error.angular.y, _x.control_error.angular.z, _x.tracking_error.linear.x, _x.tracking_error.linear.y, _x.tracking_error.linear.z, _x.tracking_error.angular.x, _x.tracking_error.angular.y, _x.tracking_error.angular.z, _x.proportional.linear.x, _x.proportional.linear.y, _x.proportional.linear.z, _x.proportional.angular.x, _x.proportional.angular.y, _x.proportional.angular.z, _x.integral.linear.x, _x.integral.linear.y, _x.integral.linear.z, _x.integral.angular.x, _x.integral.angular.y, _x.integral.angular.z, _x.derivative.linear.x, _x.derivative.linear.y, _x.derivative.linear.z, _x.derivative.angular.x, _x.derivative.angular.y, _x.derivative.angular.z, _x.feedforward.linear.x, _x.feedforward.linear.y, _x.feedforward.linear.z, _x.feedforward.angular.x, _x.feedforward.angular.y, _x.feedforward.angular.z, _x.steering_angle, _x.steering_yaw_vel, _x.steering_x_vel,) = _get_struct_36d3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_36d3f = None
def _get_struct_36d3f():
    global _struct_36d3f
    if _struct_36d3f is None:
        _struct_36d3f = struct.Struct("<36d3f")
    return _struct_36d3f
