# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_tracking_pid/PidFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PidFeedback(genpy.Message):
  _md5sum = "23bc81d441ea26241a36fb6127b9e7e4"
  _type = "path_tracking_pid/PidFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """duration eda       # Estimated (optimistic) duration remaining
float32  progress  # Progress in distance of the path traveled
"""
  __slots__ = ['eda','progress']
  _slot_types = ['duration','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       eda,progress

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PidFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.eda is None:
        self.eda = genpy.Duration()
      if self.progress is None:
        self.progress = 0.
    else:
      self.eda = genpy.Duration()
      self.progress = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2if().pack(_x.eda.secs, _x.eda.nsecs, _x.progress))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.eda is None:
        self.eda = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.eda.secs, _x.eda.nsecs, _x.progress,) = _get_struct_2if().unpack(str[start:end])
      self.eda.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2if().pack(_x.eda.secs, _x.eda.nsecs, _x.progress))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.eda is None:
        self.eda = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.eda.secs, _x.eda.nsecs, _x.progress,) = _get_struct_2if().unpack(str[start:end])
      self.eda.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2if = None
def _get_struct_2if():
    global _struct_2if
    if _struct_2if is None:
        _struct_2if = struct.Struct("<2if")
    return _struct_2if
