planners:
  - name: NavfnROS
    type: navfn/NavfnROS

controllers:
  - name: TrackingPidLocalPlanner
    type: path_tracking_pid/TrackingPidLocalPlanner

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2
plugins:
  - {name: static,           type: "costmap_2d::StaticLayer"}
  - {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
  - {name: sensor,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,        type: "costmap_2d::InflationLayer"}