planners:
  - name: NavfnROS
    type: navfn/NavfnROS

controllers:
  - name: PathTrackingPID
    type: 'path_tracking_pid/TrackingPidLocalPlanner'

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2